$tagsMap = @{
    'ben_niao_xian_fei' = @('社会对比偏差', '从众内卷偏差')
    'bai_shan_xiao_wei_xian' = @('非黑即白思维')
    'ren_yi_shi_feng_ping_lang_jing' = @('非黑即白思维')
    'cheng_wang_bai_kou' = @('非黑即白思维')
    'chu_ren_tou_di' = @('社会对比偏差')
    'jun_shi_tong_ming' = @()
    'lao_jin_cai_kong' = @()
    'fu_li_chang_liu' = @()
    'shen_xin_tong_yuan' = @()
    'ye_bu_cheng_mian' = @()
    'xian_xia_liao_yu' = @()
    'ri_ji_yue_lei' = @()
    'ge_an_qi_ming' = @()
    'shi_qu_ge_yi' = @()
    'chi_ku_fei_fu' = @()
    'tie_wan_yi_xiu' = @()
    'mian_zi_qiu_tu' = @('社会对比偏差')
    'xin_xi_jing_wa' = @('过度概括')
    'kuang_jia_qiu_tu' = @()
    'nu_li_fei_chong_fen' = @('归因谬误')
    'bian_jie_fei_ren' = @()
    'she_jiao_fei_liang' = @()
    'kong_zhi_cuo_jue' = @('归因谬误')
    'bei_gong_she_ying' = @('过度概括')
    'fu_xing_pian_cha' = @('过度概括')
    'kai_yuan_jie_liu' = @()
    'zhu_dong_zheng_qu' = @()
    'cui_hun_wei_cheng' = @('从众内卷偏差')
    'chen_mo_cheng_ben' = @('损失厌恶')
    'que_ren_pian_wu' = @('过度概括')
    'xing_cun_zhe_pian_cha' = @('幸存者偏差')
    'mao_ding_xiao_ying' = @()
    'hou_jian_zhi_ming_pian_wu' = @('归因谬误')
    'ji_ben_gui_yin_cuo_wu' = @('归因谬误')
    'ke_de_xing_qi_fa' = @('过度概括')
    'kuang_jia_xiao_ying' = @()
    'deng_ning_ke_lu_ge_xiao_ying' = @()
    'sun_shi_yan_wu' = @('损失厌恶')
    'ren_ding_sheng_tian' = @('归因谬误')
    'nan_er_you_lei_bu_qing_dan' = @('非黑即白思维')
    'qin_neng_bu_zhuo' = @('归因谬误')
    'shu_zhong_zi_you_huang_jin_wu' = @('过度概括')
    'shen_shou_bu_da_xiao_lian_ren' = @()
    'yi_ge_ba_zhang_pai_bu_xiang' = @('过度概括')
    'shi_zhe_sheng_cun' = @('归因谬误')
    'ke_lian_zhi_ren_bi_you_ke_hen_zhi_chu' = @('归因谬误')
    'jia_he_wan_shi_xing' = @()
    'tian_xia_wu_bu_shi_de_fu_mu' = @('非黑即白思维')
    'san_si_er_hou_xing' = @()
    'che_dao_shan_qian_bi_you_lu' = @()
    'tui_yi_bu_hai_kuo_tian_kong' = @()
    'yi_he_wei_gui' = @('非黑即白思维')
    'da_shi_qin_ma_shi_ai' = @('非黑即白思维')
    'jia_ji_sui_ji_jia_gou_sui_gou' = @('非黑即白思维')
    'fu_qi_mei_you_ge_ye_chou' = @()
    'lai_du_lai_le' = @('损失厌恶')
    'ren_qing_shi_gu' = @()
    'duo_yi_shi_bu_ru_shao_yi_shi' = @('损失厌恶')
    'sai_weng_shi_ma_yan_zhi_fei_fu' = @()
    'ji_suo_bu_yu_wu_shi_yu_ren' = @()
    'shou_ren_yi_yu_bu_ru_shou_ren_yi_yu' = @()
    'nv_zi_wu_cai_bian_shi_de' = @('非黑即白思维')
    'guang_zong_yao_zu' = @('社会对比偏差')
    'bu_xiao_you_san_wu_hou_wei_da' = @('从众内卷偏差')
    'hun_yu_cong_lai_bu_shi_yi_dao_xuan_ze_ti' = @('非黑即白思维')
    'hai_zi_kang_ju_xue_xi_gen_yuan' = @('归因谬误')
    'zhe_shan_wang_zhe_na_shan_gao' = @('社会对比偏差')
    'da_zhong_lian_chong_pang_zi' = @('社会对比偏差')
    'si_yao_mian_zi_huo_shou_zui' = @('社会对比偏差')
    'zuo_jing_guan_tian' = @()
    'xia_chong_bu_ke_yu_bing' = @()
    'ji_tong_ya_jiang' = @()
    'ge_hang_ru_ge_shan' = @('社会对比偏差')
    'ren_kao_yi_zhuang_ma_kao_an' = @('社会对比偏差')
    'nian_qing_jiu_yao_duo_chi_ku' = @('从众内卷偏差', '归因谬误')
    'an_wen_jiu_shi_tang_ping' = @('非黑即白思维')
    'ren_wang_gao_chu_zou' = @('社会对比偏差')
    'ao_chu_tou' = @('幸存者偏差')
    'san_shi_er_li' = @('从众内卷偏差', '社会对比偏差')
    'yi_fen_qian_yi_fen_huo' = @('过度概括')
    'neng_sheng_ze_sheng' = @('损失厌恶')
    'she_bu_de_hai_zi_tao_bu_zhe_lang' = @('损失厌恶')
    'qin_jian_jie_yue_deng_yu_kou_men' = @('非黑即白思维')
    'qiong_yang_er_fu_yang_nv' = @('非黑即白思维')
    'gong_shuo_gong_you_li_po_shuo_po_you_li' = @()
    'dao_bu_tong_bu_xiang_wei_mou' = @('非黑即白思维')
    'qian_ren_qian_mian' = @()
    'zhong_ren_jie_zui_wo_du_xing' = @()
    'wu_du_bu_zhang_fu' = @('非黑即白思维')
    'ren_bu_wei_ji_tian_zhu_di_mie' = @('归因谬误')
    'wei_nv_zi_yu_xiao_ren_nan_yang_ye' = @('非黑即白思维')
    'ren_ru_fu_zhong' = @('损失厌恶')
    'an_pin_le_dao' = @('禀赋效应')
    'yi_de_bao_yuan' = @()
    'san_ge_chou_pi_jiang_ding_ge_zhu_ge_liang' = @('过度概括')
    'jun_zi_zhi_jiao_dan_ru_shui' = @()
    'feng_ren_zhi_shuo_san_fen_hua' = @()
    'jia_jia_you_ben_nan_nian_de_jing' = @()
    'zui_du_fu_ren_xin' = @('非黑即白思维')
    'cheng_jia_li_ye' = @('从众内卷偏差')
    'pin_jian_fu_qi_bai_shi_ai' = @('归因谬误')
    'nv_ren_zhong_jiu_yao_gu_jia' = @('非黑即白思维')
    'jie_hun_cai_suan_wan_zheng' = @('从众内卷偏差')
    'men_dang_hu_dui' = @('社会对比偏差')
    'nan_zun_nv_bei' = @('非黑即白思维')
    'xian_cheng_jia_hou_li_ye' = @('从众内卷偏差')
    'wang_zi_cheng_long' = @('社会对比偏差')
    'fu_mu_du_shi_wei_ni_hao' = @('非黑即白思维')
    'gun_bang_di_xia_chu_xiao_zi' = @('归因谬误')
    'xiao_hai_zi_dong_shen_me' = @('非黑即白思维')
    'jun_zi_yuan_pao_chu' = @('非黑即白思维')
    'xue_er_you_ze_shi' = @('从众内卷偏差')
    'bu_gan_bu_jing_chi_le_mei_bing' = @('过度概括')
    'zhong_kou_cai_xia_fan' = @('过度概括')
    'ye_sheng_jiu_shi_geng_hao' = @('过度概括')
    'shao_he_shui_mei_shi' = @('过度概括')
    'ming_li_zhu_ding' = @('归因谬误')
    'xing_zuo_ding_ren_sheng' = @('归因谬误')
    'shi_pin_gai_yun' = @('归因谬误')
    'yu_shi_guai_yun_qi' = @('归因谬误')
    'jie_shi_jian_fei_yue_jian_yue_xu' = @('过度概括')
    'nong_tang_da_bu_bu_chi_rou_zhang_pang' = @('过度概括')
    'yun_qi_bi_xu_da_liang_jin_bu' = @('过度概括')
    'pian_fang_shi_liao_sheng_guo_chi_yao' = @('过度概括')
    'kao_shi_qian_qiu_fu_bai_fo' = @('归因谬误')
    'tiao_cao_kan_huang_li' = @('归因谬误')
    'sheng_bing_xian_zhao_feng_shui_xian_sheng' = @('归因谬误')
    'gen_feng_wang_hong_xiao_fei' = @('从众内卷偏差')
    'yong_she_chi_pin_zheng_ming_zhi_chang_di_wei' = @('社会对比偏差')
    'fu_mu_bu_dong_wo' = @()
    'di_yu_qi_shi' = @('过度概括')
    'bie_ren_jia_de_hai_zi' = @('社会对比偏差')
    'san_shi_wu_sui_men_kan' = @('社会对比偏差')
    'xue_li_jue_ding_yi_qie' = @('过度概括')
    'wei_hai_zi_xi_sheng_suo_you' = @('损失厌恶')
    'you_qian_cai_you_yi_qie' = @('社会对比偏差')
    'chen_nian_qing_pin_ming_gao_qian' = @('从众内卷偏差')
    'bie_ren_du_juan_wo_bu_nu_li_jiu_luo_hou' = @('从众内卷偏差')
    'cu_cha_dan_fan' = @('过度概括')
    'bing_cong_kou_ru' = @('过度概括')
    'shi_bu_yan_jing_kuai_bu_yan_xi' = @('过度概括')
    'chen_re_chi' = @('过度概括')
    'he_bai_zhou_yang_wei' = @('过度概括')
    'he_gu_tou_tang_bu_gai' = @('过度概括')
    'yi_guan_chu_chu' = @('社会对比偏差')
    'xin_san_nian_jiu_san_nian' = @('损失厌恶')
    'zhi_chuan_gui_de_bu_chuan_dui_de' = @('社会对比偏差')
    'yao_li_rong_jiu_shi_qiong_ren_de_diao' = @('社会对比偏差')
    'an_ju_le_ye' = @('从众内卷偏差')
    'jin_wo_yin_wo_bu_ru_zi_ji_de_gou_wo' = @('禀赋效应')
    'fu_bu_zhu_da_wu_qiong_bu_xing_yuan_lu' = @('损失厌恶')
    'mai_fang_cai_ti_mian_zu_fang_shi_guo_du' = @('社会对比偏差')
    'an_bu_dang_che' = @('损失厌恶')
    'zou_ma_guan_hua' = @('从众内卷偏差')
    'xing_wan_li_lu_du_wan_juan_shu' = @()
}

$json = Get-Content 'app\src\main\assets\idioms\idioms.json' -Raw -Encoding UTF8 | ConvertFrom-Json

$processed = 0
$skipped = 0

foreach ($item in $json) {
    $id = $item.id
    if ($item.PSObject.Properties.Name -contains 'cognitiveBiasTags') {
        $skipped++
        continue
    }
    if ($tagsMap.ContainsKey($id)) {
        $item | Add-Member -NotePropertyName 'cognitiveBiasTags' -NotePropertyValue $tagsMap[$id] -Force
        $processed++
    } else {
        Write-Host "Warning: No tags found for id: $id"
        $item | Add-Member -NotePropertyName 'cognitiveBiasTags' -NotePropertyValue @() -Force
        $processed++
    }
}

$json | ConvertTo-Json -Depth 10 | Out-File 'app\src\main\assets\idioms\idioms.json' -Encoding UTF8

Write-Host "Processed: $processed, Skipped: $skipped, Total: $($json.Count)"
